In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
from evaluator import Evaluator
import os
import matplotlib.pyplot as plt
import IPython.html.widgets as w
import utils
%matplotlib inline

/home/htang6/anaconda2/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [2]:
filename = '/home/htang6/workspace/nod/training/detector/filenames_elephant.npy'
data_dir = '/home/htang6/preprocess_result/'
filename = np.load(filename)

In [3]:
print filename

['chu_zaiyong_20170915_204327111' 'chen_shanghong_20170915_124630458'
 'chen_tingting_20170915_133452526' 'chen_guoqiang_20170915_175857926'
 'dong_shuping_20170915_130056185' 'an_huajun_20170915_153907038'
 'cao_cheng_20170915_143050807' 'chu_milan_20170915_105056865'
 'chen_donglin_20170915_132623387' 'dang_zhengquan_20170915_171709778'
 'chu_dejun_20170916_200905492' 'cui_fei_20170915_203141679'
 'chen_liguang_20170915_135022426']


In [4]:
patient = filename[5]
img = np.load(os.path.join(data_dir, '%s_clean.npy' % (patient)))

In [5]:
# plt.imshow(imgs[40], cmap='gray')
# plt.show()
# e = evaluator('elephant/', 'test', '/home/htang6/workspace/nod/training/detector/filenames_elephant.npy, ckpt=i,pbb_cutoff=0.5)
def fz(k):
    plt.rcParams['figure.figsize'] = (16.0, 8.0)
    plt.imshow(img[k], cmap='gray')

w.interact(fz, k=w.IntSlider(min=0,max=img.shape[0]-1,step=1,value=0))

A Jupyter Widget

<function __main__.fz>

In [18]:
e = Evaluator('elephant/', 'test', '/home/htang6/workspace/nod/training/detector/filenames_elephant.npy', ckpt=95,pbb_cutoff=0.5)

In [35]:
e.PREP

'/home/htang6/preprocess_result'

In [21]:
res = '/home/htang6/workspace/nod/training/detector/results/elephant/bbox/elephant_095/'
pbb = np.load(os.path.join(res, '%s_pbb.npy' % (patient)))

In [34]:
print pbb[:10]
n = 2
z, y, x, d = pbb[n][1], pbb[n][2], pbb[n][3], pbb[n][4]
def fz(k):
    utils.showTargetImgComp(img, [k,y,x], plt, d=d, t=str(patient))
#     plt.rcParams['figure.figsize'] = (16.0, 8.0)
#     plt.imshow(img[k], cmap='gray')


w.interact(fz, k=w.IntSlider(min=0,max=img.shape[0]-1,step=1,value=z))

[[   4.06543732  126.20900726   56.83874512   86.20251465    6.03859043]
 [   3.44784188  156.5027771    54.14354324   86.29499054    5.77470303]
 [   2.49460006  125.35141754  161.67379761  214.40551758    5.85423183]
 [   1.87616575  198.62382507   86.215271    106.23899078    5.59163618]
 [   1.74383461  101.72181702   38.11397171  238.36517334    5.37033367]
 [   1.54833364  132.87101746   84.73021698  230.07189941    9.30238438]
 [   1.37440681  133.17575073   64.68791962   87.99475098   10.28957081]
 [   1.31388021  113.4196701   129.10031128   80.46769714    9.95795727]
 [   1.18159974  113.995224    113.29669189   42.15019608    5.55807447]
 [   1.17538476  181.00769043  101.37924957  200.93838501   11.20460224]]


A Jupyter Widget

<function __main__.fz>